services:
  - type: web
    name: sport-cov
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Api-Fastapi:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_API_KEY
        sync: true
