name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * *"   # tous les jours à 05:00 UTC (~07:00 en France l’hiver)
  workflow_dispatch:       # lancement manuel depuis Actions

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint (ruff)
        run: |
          ruff check . --line-length 120 \
            --ignore B904,UP006,UP035,SIM115 \
            --per-file-ignores='api_fastapi.py:E402,api_fastapi.py:I001'
      - name: Type check (mypy)
        run: mypy .
      - name: Security (bandit)
        run: bandit -x tests -s B101 -r .
      - name: Dependencies audit
        run: pip-audit -r requirements.txt || true  # d’abord en warning
      - name: Tests
        run: pytest -q

name: Uptime Ping
on:
  schedule:
    - cron: "*/30 * * * *"      # toutes les 30 min (exemple)
  workflow_dispatch:


  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        env:
          RENDER_HOST: ${{ secrets.RENDER_HOST }}   # <-- secret GitHub
        run: |
          if [ -z "$RENDER_HOST" ]; then
            echo "Secret RENDER_HOST manquant"; exit 1
          fi
          curl -fsS --max-time 15 --retry 3 --retry-all-errors \
            "https://${RENDER_HOST}/health" > /dev/null
          echo "Ping OK"
