name: CI

on:
  push:
  pull_request:
  # schedule:
  #   - cron: "0 5 * * *"   # 1 fois par jour à 05:00 UTC
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (ruff)
        run: |
          ruff check . --line-length 120 \
            --ignore B904,UP006,UP035,SIM115 \
            --per-file-ignores 'api_fastapi.py:E402,I001'

      - name: Type check (mypy)
        run: mypy .

      - name: Security (bandit)
        run: bandit -x tests -s B101 -r .

      - name: Dependencies audit
        run: pip-audit -r requirements.txt || true

      - name: Tests
        run: pytest -q

  ping:
    if: github.event_name == 'workflow_dispatch'   # ne tourne que si lancé manuellement
    runs-on: ubuntu-latest
    steps:
      - name: Check API live
        env:
          RENDER_HOST: ${{ secrets.RENDER_HOST }}   # ex: mon-api.onrender.com (sans https://)
        run: |
          if [ -z "$RENDER_HOST" ]; then
            echo "❌ Secret RENDER_HOST manquant"; exit 1
          fi
          # Debug rapide
          curl -i "https://${RENDER_HOST}/docs" || true
          # Ping strict (avec retries)
          curl -fsS --max-time 15 --retry 3 --retry-all-errors \
            "https://${RENDER_HOST}/docs" > /dev/null
          echo "✅ Ping OK"

  e2e:
    name: Cypress E2E (Render)
    needs: quality
    runs-on: ubuntu-latest
    env:
      # variables lues par Cypress via Cypress.env('...')
      CYPRESS_E2E_LOGIN_EMAIL:    ${{ secrets.E2E_LOGIN_EMAIL }}
      CYPRESS_GMAIL_USER:         ${{ secrets.GMAIL_USER }}
      CYPRESS_GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Check Cypress env present
        shell: bash
        run: |
          for v in CYPRESS_E2E_LOGIN_EMAIL CYPRESS_GMAIL_USER CYPRESS_GMAIL_APP_PASSWORD; do
            if [ -z "${!v}" ]; then echo "❌ $v manquant"; exit 1; else echo "✅ $v défini"; fi
          done

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node deps
        run: npm ci

      - name: Prepare debug dir
        run: |
          mkdir -p cypress/_debug
          : > cypress/_debug/network.log

      # (optionnel) réveille l’API Render
      - name: Warmup API
        env:
          RENDER_HOST: ${{ secrets.RENDER_HOST }}
        run: |
          if [ -n "$RENDER_HOST" ]; then
            curl -fsS "https://${RENDER_HOST}/openapi.json" >/dev/null || true
          fi

      - name: Cypress (PROD - FRONT)
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_E2E_LOGIN_EMAIL:    ${{ secrets.E2E_LOGIN_EMAIL }}
          CYPRESS_GMAIL_USER:         ${{ secrets.GMAIL_USER }}
          CYPRESS_GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        with:
          install: false
          wait-on: ${{ secrets.FRONT_BASEURL }}          # on attend le FRONT
          wait-on-timeout: 120000
          config: baseUrl=${{ secrets.FRONT_BASEURL }}   # baseUrl côté Cypress

      # Artefacts utiles si ça casse
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload network logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-network-logs
          path: cypress/_debug
          if-no-files-found: warn

      - name: Tail network log (last 200 lines)
        if: failure()
        run: |
          echo "---- tail cypress/_debug/network.log ----"
          tail -n 200 cypress/_debug/network.log || true
